version: "3.6"
services:
  goservice:
    build: "./backend"
    ports:
      - "8094:8080"
  nginx:
    build: "./nginx"
    ports:
      - "8085:8085"
    depends_on:
      - "goservice"
      - "front"
  front:
    build: "./frontend"
    ports:
      - "8082:8080"